set(_CATKIN_CURRENT_PACKAGE "simumap")
set(simumap_VERSION "0.0.0")
set(simumap_MAINTAINER "louis <louis@todo.todo>")
set(simumap_PACKAGE_FORMAT "2")
set(simumap_BUILD_DEPENDS "rospy" "roscpp" "std_msgs" "sensor_msgs" "nav_msgs" "cv_bridge" "image_transport")
set(simumap_BUILD_EXPORT_DEPENDS "rospy" "roscpp" "std_msgs" "sensor_msgs" "nav_msgs" "cv_bridge" "image_transport")
set(simumap_BUILDTOOL_DEPENDS "catkin")
set(simumap_BUILDTOOL_EXPORT_DEPENDS )
set(simumap_EXEC_DEPENDS "rospy" "roscpp" "std_msgs" "sensor_msgs" "nav_msgs" "cv_bridge" "image_transport")
set(simumap_RUN_DEPENDS "rospy" "roscpp" "std_msgs" "sensor_msgs" "nav_msgs" "cv_bridge" "image_transport")
set(simumap_TEST_DEPENDS )
set(simumap_DOC_DEPENDS )
set(simumap_URL_WEBSITE "")
set(simumap_URL_BUGTRACKER "")
set(simumap_URL_REPOSITORY "")
set(simumap_DEPRECATED "")